---
- name: Set password 
  hosts: users 
  become: yes

  tasks:
  - name: Set passwd 
    user:
      name: ansible01
      update_password: always  # or can use on_create
      password: "{{ 'root' | password_hash('sha512', 'mysalt123') }}"
